dependencies:
  # - <organization/repo>@<version>
  # La ligne suivante est pour dire où se trouve les fichiers (Repository Github) désirés sur Github (à la place de NPM dans notrre cas)
  # Ca va donc downloader les sources
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
       # Ceci dit au compiler que @chainlink --> smartcontractkit/chainlink-brownie-contracts@1.1.1, donc @chainlink va pointer sur le Repository Github
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
